ADR 17: Enable container autodiscovery to scan images from private repos
secureCodeBox/secureCodeBox pull request #1374
Opened 2022-09-20 09:30 UTC by the-simmon

First draft, mostly brain storming, feel free to commit to this branch :) (this time with correct adr number)

2022-09-28 10:02 UTC, SebieF reviewed
Very nice work, thank you :) Only few minor comments from my side.

It might be worth to include the trivy operator and k8s scan functionality as an additional possibility? Other than that, I really like the sidecar proposal and that one is already very sophisticated thanks to your example!

2022-10-05 12:27 UTC, the-simmon commented
> Very nice work, thank you :) Only few minor comments from my side.
> 
> It might be worth to include the trivy operator and k8s scan functionality as an additional possibility? Other than that, I really like the sidecar proposal and that one is already very sophisticated thanks to your example!

I don think it is possible to incorporate the trivy operator into the scb as it functions differently. I looked at the trivy docs and added the idea to use ownerReferences to delete the secret after the scan is done to this adr.

2022-11-23 11:53 UTC, Weltraumschaf requested changes
LGTM. Did some suggestions.

2022-11-23 11:53 UTC, Weltraumschaf commented on docs/adr/adr_0017.md
> +SPDX-License-Identifier: Apache-2.0
```suggestion
SPDX-License-Identifier: Apache-2.0
title: "ADR-0017: Enable Container Autodiscovery To Scan Container Images From Private Registries
sidebar_label: "ADR-0017"
```

2022-11-23 11:53 UTC, Weltraumschaf commented on docs/adr/adr_0017.md
> +# ADR-0017: Enable container autodiscovery to scan container images from private registries
```suggestion
# ADR-0017: Enable Container Autodiscovery To Scan Container Images From Private Registries
```

2022-11-23 11:53 UTC, Weltraumschaf commented on docs/adr/adr_0017.md
> +| **Author(s)**: | Simon Hülkenberg <simon.huelkenberg@iteratec.com> |
```suggestion
| **Author(s)**: | Simon Hülkenberg <simon.huelkenberg@iteratec.com>, Sven Strittmatter <sven.strittmatter@iteratec.com> |
```

2022-11-23 11:53 UTC, Weltraumschaf commented on docs/adr/adr_0017.md
> +### Problem regarding imagePullSecretes
```suggestion
### Problem Regarding imagePullSecretes

```

2022-11-23 11:53 UTC, Weltraumschaf commented on docs/adr/adr_0017.md
> +### Possible solutions
```suggestion
### Possible Solutions

```

2022-11-23 11:53 UTC, Weltraumschaf commented on docs/adr/adr_0017.md
> +#### Using an initContainer and a sidecar
```suggestion
#### Using an initContainer and a Sidecar

```

2022-11-23 11:53 UTC, Weltraumschaf commented on docs/adr/adr_0017.md
> +Pros:
```suggestion

##### Pros

```

2022-11-23 11:53 UTC, Weltraumschaf commented on docs/adr/adr_0017.md
> +Cons:
```suggestion
##### Cons:

```

2022-11-23 11:53 UTC, Weltraumschaf commented on docs/adr/adr_0017.md
> +<details><summary> Proof of concept</summary>
```suggestion

<details>
<summary> Proof of concept</summary>

```

2022-11-23 11:53 UTC, Weltraumschaf commented on docs/adr/adr_0017.md
> +#### Using an initContainer and use ownerReferences for the created secretes
```suggestion
#### Using an initContainer and Use ownerReferences for the Created Secretes

```

2022-11-23 11:53 UTC, Weltraumschaf commented on docs/adr/adr_0017.md
> +Pros:
```suggestion
##### Pros

```

2022-11-23 11:53 UTC, Weltraumschaf commented on docs/adr/adr_0017.md
> +#### Using a separate operator
```suggestion
#### Using a Separate Operator

```

2022-11-23 11:53 UTC, Weltraumschaf commented on docs/adr/adr_0017.md
> +Pros:
```suggestion
##### Pros

```

2022-11-23 11:53 UTC, Weltraumschaf commented on docs/adr/adr_0017.md
> +Cons:
```suggestion
##### Cons

```

2022-12-13 19:53 UTC, Weltraumschaf approved these changes

2022-12-13 19:54 UTC, Weltraumschaf commented
@the-simmon Can't rebase. You must rebase by your own.

2022-12-16 15:00 UTC, merged