Fix / Upgrade `controller-tools` Version in Make Files
secureCodeBox/secureCodeBox pull request #1398
Opened 2022-10-11 11:30 UTC by J12934

Was likely not correctly updated during the latest kubebuilder upgrade

2022-10-11 16:38 UTC, Weltraumschaf requested changes

2022-10-25 10:51 UTC, J12934 commented on operator/controllers/execution/suite_test.go
> +		ErrorIfCRDPathMissing: true,
yes good point, i've changed it 👍

2022-10-25 10:52 UTC, J12934 commented on auto-discovery/kubernetes/Makefile
> +ENVTEST_K8S_VERSION = 1.24.2
yes, i'd prefer to do this in a seperrate merge as we'd ideally inject this from the pipeline which also has supported k8s versions defined.

2022-11-02 11:54 UTC, the-simmon approved these changes

2022-11-18 12:48 UTC, merged