Make userid optional for defectdojo
secureCodeBox/secureCodeBox pull request #1412
Opened 2022-10-19 15:14 UTC by the-simmon

This PR solves https://github.com/secureCodeBox/secureCodeBox/issues/783.
It depends on this [PR](https://github.com/secureCodeBox/defectdojo-client-java/pull/25) from the `defectdojo-client-java` repo. So merge the other PR before this one.

2022-11-18 13:16 UTC, Weltraumschaf commented on hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/strategies/VersionedEngagementsStrategy.java
> +      userId = userProfileService.search().get(0).getUser().getId();
This looks like a possible IOOBE: If the collection returned by `search()` the `get(0)` will throw an `IndexOutOfBoundException.

2022-12-13 19:21 UTC, Weltraumschaf reviewed
Why is this test not needed anymore? In the subject under test you have two cases: One element as expected or empty list. Now you test neither.

2022-12-16 12:23 UTC, the-simmon commented
> Why is this test not needed anymore? In the subject under test you have two cases: One element as expected or empty list. Now you test neither.

You are right. Fixed the unit test to use the correct service now.

2022-12-16 15:06 UTC, Weltraumschaf approved these changes

2022-12-19 10:03 UTC, Weltraumschaf approved these changes

2022-12-19 10:31 UTC, Weltraumschaf commented
@the-simmon Java test failes.

2023-01-08 12:33 UTC, the-simmon commented
> @the-simmon Java test failes.

yes because you have to merge the pr linked in the description first because i changed the defect-dojo-client version in build.gradle

2023-01-10 12:37 UTC, Weltraumschaf commented
https://github.com/secureCodeBox/defectdojo-client-java/pull/25 merged

2023-01-10 21:05 UTC, Weltraumschaf commented
@the-simmon Do we need to release the client beforehand?

2023-01-17 12:09 UTC, the-simmon commented
> @the-simmon Do we need to release the client beforehand?

yes, good point

2023-01-25 14:34 UTC, rseedorff commented
@the-simmon you can now use the version `0.0.40-SNAPSHOT` which contains the latest changes in the underlying defectdojo-client lib.

2023-01-25 14:34 UTC, rseedorff requested changes

2023-01-25 14:34 UTC, rseedorff commented on hooks/persistence-defectdojo/hook/build.gradle
> +  implementation 'io.securecodebox:defectdojo-client:0.0.38-SNAPSHOT'
```suggestion
  implementation 'io.securecodebox:defectdojo-client:0.0.40-SNAPSHOT'
```

2023-01-25 19:17 UTC, Weltraumschaf approved these changes

2023-01-25 19:18 UTC, merged