Create a download cache for trivy database (closes #911)
secureCodeBox/secureCodeBox pull request #1760
Opened 2023-06-09 15:56 UTC by o1oo11oo

## Description

This uses the trivy client/server functionality to download the vulnerability DB only once for multiple scans to avoid GitHub's rate limit. An additional container running trivy in server mode is started, and all scans connect to it. This integrates the functionality previously documented [in the SCB docs for trivy][1], now that trivy supports remote scanning for more than just container image scans. Client/server support for other scan types was added in aquasecurity/trivy#1829 and aquasecurity/trivy#3131.

Closes #911.

[1]: https://www.securecodebox.io/docs/scanners/trivy/#scanning-many-targets

### Checklist

* [ ] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] Make sure that all your commits are signed-off and that you are added to the [Contributors](https://github.com/secureCodeBox/secureCodeBox/blob/main/CONTRIBUTORS.md) file.
* [ ] Make sure that all CI finish successfully.
* [x] Optional (but appreciated): Make sure that all commits are [Verified](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

2023-06-13 06:01 UTC, J12934 requested changes
Looks really good 👍
One major thing missing is mentioning it in the docs. How it works and how it can be disabled and why somebody would want to do that.
Also the existing caching docs should then be tweaked as the no longer make much sense now that we have this in place.

2023-06-14 09:06 UTC, o1oo11oo commented on scanners/trivy/templates/trivy-database-cache.yaml
> +  replicas: 1
I've looked into kubernetes scaling and autoscaling but I guess it's enough to move this values so it can be configured at least?

2023-06-14 11:44 UTC, o1oo11oo commented on scanners/trivy/templates/trivy-database-cache.yaml
> +      - name: trivy-database
Trivy server has a `/healthz` endpoint (see aquasecurity/trivy#534) which can be used for liveness checks. According to the logs/stdout trivy server first downloads the DB and then starts listening, so using it for liveness/readiness checks should work. That's also what's used in the helm chart provided by trivy (aquasecurity/trivy#751).

2023-06-14 11:45 UTC, o1oo11oo commented on scanners/trivy/templates/trivy-database-cache.yaml
> +        imagePullPolicy: Always
That's just a copy/paste from the docs, no reason to keep it.

2023-06-14 12:25 UTC, o1oo11oo commented
I've tested what happens when the trivy server cannot download the database, and it just exits with an error, so the pod gets restarted and then runs into CrashLoopBackoff. Since I didn't define a dependency on the cache service (other than using the url in a parameter), would the scan even wait for the cache to be ready?

2023-06-27 15:45 UTC, J12934 approved these changes

2023-06-28 08:27 UTC, merged