Adjust to refactoring in defectdojo-client-java
secureCodeBox/secureCodeBox pull request #1812
Opened 2023-07-17 13:30 UTC by Zero3141

## Description
Adjustments to refactoring in defectdojo-client-java. Further needed for [#29](https://github.com/secureCodeBox/defectdojo-client-java/issues/29)

### Checklist

* [ ] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [ ] Make sure that all your commits are signed-off and that you are added to the [Contributors](https://github.com/secureCodeBox/secureCodeBox/blob/main/CONTRIBUTORS.md) file.
* [ ] Make sure that all CI finish successfully.
* [ ] Optional (but appreciated): Make sure that all commits are [Verified](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

2023-07-17 13:36 UTC, Zero3141 commented
[PR #43](https://github.com/secureCodeBox/defectdojo-client-java/pull/43) must be published to maven central first before merging

2023-07-18 07:49 UTC, Weltraumschaf requested changes
Added one suggestion.

2023-07-18 07:49 UTC, Weltraumschaf commented on hooks/persistence-defectdojo/hook/src/test/java/io/securecodebox/persistence/service/ScanServiceTest.java
> +    File resourceFile = new File(resourceURI);
It is not necessary to use file here. You can directly convert URI to Path: `Path.get(uri)`.

2023-07-19 15:40 UTC, Weltraumschaf approved these changes

2023-07-19 15:53 UTC, merged