Remove duplicate sponsor images from documentation
secureCodeBox/secureCodeBox pull request #1944
Opened 2023-09-11 09:47 UTC by Zero3141

## Description
Part of [#942](https://github.com/secureCodeBox/secureCodeBox/issues/942)

### Checklist

* [ ] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [ ] Make sure that all your commits are signed-off and that you are added to the [Contributors](https://github.com/secureCodeBox/secureCodeBox/blob/main/CONTRIBUTORS.md) file.
* [ ] Make sure that all CI finish successfully.
* [ ] Optional (but appreciated): Make sure that all commits are [Verified](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

2023-09-11 11:04 UTC, Weltraumschaf requested changes
We should remove any unnecessary code to build things. So IMO the images should reside in the docusaurus folder, so we do not need to move them around. In the main README we can simply deep link to these files.

Also we should consider if we can simplify the scanner/hooks docs generation, to get rid ofthe untested build scripts.

2023-09-11 11:04 UTC, Weltraumschaf commented on documentation/src/utils/config.js
> +    targetPath: ".", // This needs to be '.' as files copied to docs (scanners & hooks) and static (sponsors) folder
Id do not really understand the comment here.

2023-09-11 11:04 UTC, Weltraumschaf commented on documentation/src/utils/config.js
> +        src: "resources/sponsors",
Why that? We can simply reference the images IMO in the main README directly, right?

2023-09-12 08:49 UTC, Zero3141 commented
Replaced by https://github.com/secureCodeBox/secureCodeBox/pull/1950

2023-09-12 08:49 UTC, closed without merging