Add licenses to missing files
secureCodeBox/secureCodeBox pull request #1965
Opened 2023-09-15 12:43 UTC by Zero3141

## Description
Add license information for several files. Dependence for [PR1961](https://github.com/secureCodeBox/secureCodeBox/pull/1961)

### Checklist

* [ ] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [ ] Make sure that all your commits are signed-off and that you are added to the [Contributors](https://github.com/secureCodeBox/secureCodeBox/blob/main/CONTRIBUTORS.md) file.
* [ ] Make sure that all CI finish successfully.
* [ ] Optional (but appreciated): Make sure that all commits are [Verified](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

2023-09-18 08:02 UTC, Zero3141 commented
Only files from the documentation folder are missing now

2023-09-20 14:52 UTC, Weltraumschaf requested changes
See my comment.

2023-09-20 14:52 UTC, Weltraumschaf commented on .reuse/dep5
> +Files: .github/*.md
Here should go the path to the issue templates, right?

2023-09-21 18:46 UTC, Weltraumschaf approved these changes

2023-09-21 18:46 UTC, merged