Bugfixing some hook HelmChart issues
secureCodeBox/secureCodeBox pull request #260
Opened 2020-12-23 21:12 UTC by rseedorff

## Checklist

* [ ] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [ ] Make sure `npm test` runs for the whole project.

## Description

* Bugfixing some hook HelmChart issues like typos and missing documentation

2020-12-28 07:48 UTC, fuhrmeistery approved these changes

2020-12-28 07:50 UTC, fuhrmeistery commented
There are some signing issues. This PR has to be merged by an admin

2020-12-28 10:05 UTC, J12934 requested changes

2020-12-29 12:31 UTC, J12934 approved these changes

2020-12-29 12:31 UTC, merged