#2605 Adapt Json Parsing for sslyze 6.0.0
secureCodeBox/secureCodeBox pull request #2673
Opened 2024-09-24 12:25 UTC by BorisShek

Upgrade sslyze to 6.0.0.
Update all JSON test files and parser.test.js to be compatible with sslyze 6.0.0 JSON output. Remove mixed-connectivity-result.json as it is no longer used in parser.test.js. Adjust JSON output for "self-signed.badssl.com" due to sslyze 6.0.0's migration to Python Cryptography for certificate validation. Validation errors for "self signed certificate" and "self signed certificate in certificate chain" now return as "validation failed: Other('Certificate is missing required extension')". Update the "matchesHostname" logic to align with sslyze 6.0.0's new validation approach.

## Description

### Checklist

* [ ] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] Make sure that all your commits are signed-off and that you are added to the [Contributors](https://github.com/secureCodeBox/secureCodeBox/blob/main/CONTRIBUTORS.md) file.
* [ ] Make sure that all CI finish successfully.
* [x] Optional (but appreciated): Make sure that all commits are [Verified](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

2024-09-24 20:10 UTC, BorisShek commented
Resolves #2605

2024-10-06 00:11 UTC, J12934 requested changes
Awesome, looks good :)
Only one minor thing i noticed, otherwise it should be ready to go :+1:

2024-10-06 00:11 UTC, J12934 commented on scanners/sslyze/parser/parser.js
> +    console.log(certificateInfos)
```suggestion
```

2024-10-06 00:11 UTC, J12934 commented on scanners/sslyze/parser/parser.js
> +  const isSelfSigned = leafCertificate.subject.rfc4514_string === leafCertificate.issuer.rfc4514_string;
Ah cool you found a way to still have the self signed check :+1:

2024-10-11 11:15 UTC, J12934 approved these changes

2024-10-11 11:16 UTC, merged