Release And Bugfixing Strategy
secureCodeBox/secureCodeBox pull request #353
Opened 2021-03-30 17:08 UTC by fuhrmeistery

We had a discussion about our release management and these are the main
points we want to clarify

Signed-off-by: Yannik Fuhrmeister <yannik.fuhrmeister@protonmail.com>

2021-03-31 21:01 UTC, rseedorff approved these changes

2021-04-06 11:10 UTC, twwd requested changes
I

2021-04-06 11:10 UTC, twwd commented on SECURITY.md
> +If you are interessted in extended support for older versions with security updates of our project
```suggestion
If you are interested in extended support for older versions with security updates of our project 
```

2021-04-06 11:10 UTC, twwd commented on SECURITY.md
> +please get in touch with the project team via Slack or eMail <secureCodeBox@iteratec.com>.
```suggestion
please get in touch with the project team via Slack or email <secureCodeBox@iteratec.com>.
```

2021-04-06 11:10 UTC, twwd commented on SECURITY.md
> +Please get in touch with the project team via Slack or eMail <secureCodeBox@iteratec.com>.
```suggestion
Please get in touch with the project team via Slack or email <secureCodeBox@iteratec.com>. 
```

2021-04-06 11:10 UTC, twwd commented on SECURITY.md
> +You have found a vulnerability in the project that shouldndt be discloused as public issue before its fixed?
```suggestion
You have found a vulnerability in the project that shouldn't be disclosed as public issue before it's fixed?
```

2021-04-06 11:10 UTC, twwd commented on SECURITY.md
> +We currently plan to provide support for the _latest minor [semver](https://semver.org/lang/de/)_ release only.
```suggestion
We currently plan to provide support for the _latest minor [semver](https://semver.org/)_ release only.
```

2021-04-06 11:10 UTC, twwd commented on SECURITY.md
> +Our _release cycle_ for new features (minior [semver](https://semver.org/lang/de/) update)
```suggestion
Our _release cycle_ for new features (minior [semver](https://semver.org/) update)
```

2021-04-10 20:57 UTC, merged