Update nikto scanner to 2.5.0 (closes #604)
secureCodeBox/secureCodeBox pull request #617
Opened 2021-08-30 16:03 UTC by Ilyesbdlala

## Description

This PR updates the nikto scanner to 2.5.0. The main reason for it is to solve the issue the scanner has, when parsing findings from an unresolvable host (Issue #604).
Updating also results into more findings.
It should be noted that with this PR, Nikto scanner relies on the github repo having a 2.5.0 branch. The `ci.yaml` has to be changed if the 2.5.0 becomes in the release branch.

### Checklist

* [X] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [X] Make sure `npm test` runs for the whole project.
* [X] Make codeclimate checks happy

2021-09-03 07:49 UTC, JohannesZahn requested changes
With everything else we'll have to wait on more feedback on sullo/nikto#742

2021-09-03 07:49 UTC, JohannesZahn commented on scanners/nikto/examples/demo-bodgeit/findings.yaml
>      "name": "The anti-clickjacking X-Frame-Options header is not present.",
cut this down to 5 findings. These examples are rendered on the docs website and 5 should be sufficient. Also do this for the other findings in the examples folder.

2021-09-03 07:49 UTC, JohannesZahn commented on scanners/nikto/examples/demo-bodgeit/nikto-results.json
>  {
I think we can get rid of this file. In the examples folder we don't need any raw results, only in the tests. Please also delete the juice-shop one.

2021-09-13 08:22 UTC, fuhrmeistery requested changes

2021-09-13 08:22 UTC, fuhrmeistery commented on .github/workflows/ci.yaml
> +          ref: nikto-2.5.0
I think it would be great to create a variable containing the desired version to minimize the locations we have to update for a new release

2021-09-13 08:22 UTC, fuhrmeistery commented on scanners/nikto/parser/parser.test.js
> +test("parses no web server found finding correctly", async () => {
```suggestion
test("parses 'no web server found' finding correctly", async () => {
```
I think this could improve readability

2021-09-27 15:51 UTC, Ilyesbdlala commented
This pull request is now stale (due to #610). Further development is on PR #668

2021-09-27 15:51 UTC, closed without merging