[SCB-Bot] Upgraded gitleaks from v7.6.1 to v8.0.0
secureCodeBox/secureCodeBox pull request #830
Opened 2021-11-23 09:30 UTC by secureCodeBoxBot

"This is an automated Pull Request by the SCB-Bot. It upgrades gitleaks from v7.6.1 to v8.0.0"
## Release changes :
Gitleaks v8.0.0 introduces some breaking changes and feature removals. My vision for gitleaks is for the project to
 follow the [unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) -- do one thing and one thing well. 
 That one thing is detecting secrets efficiently.
 
 Sorry if this causes any inconveniences. You can always fork older versions of Gitleaks. 
 
 ### What's changed
 - Swapped `go-git` for shelling out `git log -p` and `git diff` commands when scanning/protecting git repos
 - See comparison [metrics/chart](https://github.com/zricethezav/gitleaks/issues/683#issuecomment-969168273) 🌎 🍃
 - Memory Usage from running gitleaks on the [gitleaks](https://github.com/zricethezav/gitleaks) repo: **54MB -> 8.5MB**
 - Simplified call stack
 - Faster scans 
 - [ghrc support](https://github.com/zricethezav/gitleaks/pkgs/container/gitleaks)
 - Added `detect`, `protect`, `help`, and `version` commands to reduce number of options
 - Support for multiline regular expressions in rules
 - Added `StartLine`, `EndLine`, `StartColumn`, `EndColumn` to report findings
 - Added `RuleID` to report findings
 - CLI powered by `spf13/cobra`
 - Removed `repo-config` support
 - This can be scripted 
 - Default config path added `(--source/-s)/.gitleaks.toml`, see usage for more details
 - Removed cloning support
 - I do not want gitleaks to be responsible for cloning repositories
 - Removed `files at commit` support
 - This can be accomplished by `git checkout`
 - Removed all `commit` options
 - All commit options can be supported by the `--log-opts` argument. `--log-opts` accepts any `git log` options.
 - All log messages sent to stderr
 - Finding output (enabled with `-v`/`--verbose`) sent to stdout.
 - This can be paired with `jq` to do additional filtering
 - **Added 60+ rules** to best maintain parity with https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning#about-secret-scanning-for-private-repositories
 - https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml
 - [Updated Config](https://github.com/zricethezav/gitleaks#configuration)
 --- 
 
 If you find any bugs or issues related to this release please open an issue or PR with the tag `v8`.
 
 If Gitleaks has brought you commercial success please consider supporting me via Github [sponsors](https://github.com/sponsors/zricethezav), like [Typeform](https://github.com/Typeform-sponsorships). Typeform recently donated $1000 and wrote a very nice blog post about [preventing secret leaks at scale](https://medium.com/typeforms-engineering-blog/prevent-secrets-leaks-at-scale-in-repositories-e785b96e8244).

2021-11-23 09:34 UTC, malexmave commented
Oh my. This is going to be a larger operation if we include it. Let's discuss what to do about this once we have our team together again.

2021-12-08 11:23 UTC, malexmave commented
What will have to be done here:
- [ ] Pull the version number up to the latest 8.X (there have been more releases)
- [ ] Update the parser
- [ ] Update the unit tests
- [ ] Update the documentation (no more cloning directly from GitLeaks => use init containers, as [described here](https://docs.securecodebox.io/blog/2021/10/27/sast-scanning) for example)
- [ ] Re-enable the version check in the CI files for SCB Bot

2022-01-25 14:15 UTC, malexmave commented
This is now ready to review. Please also review with an eye towards https://github.com/secureCodeBox/documentation/issues/160 so that we may be able to close that as well.

2022-03-07 10:01 UTC, SebieF requested changes
A lot of nice work! Only a few comments/questions from my side. :)

2022-03-10 11:41 UTC, malexmave commented on scanners/gitleaks/examples/secureCodeBox/findings.json
> +[
Yes. I shortened it because it would make the site unusable if I include a massive JSON file (see the last couple of lines) :).

2022-03-10 12:17 UTC, malexmave commented on scanners/gitleaks/Makefile
Hmm. Can't reproduce, it works fine on my machine. I suspect that the parser image is not available in your cluster, as [this is something `make integration-tests` does not take care of](https://github.com/secureCodeBox/secureCodeBox/issues/756). Assuming you are running with kind, can you run the following commands:

```bash
# Start in the project root
cd parser-sdk/nodejs
make docker-build-sdk
cd ../../scanners/gitleaks
make docker-build
make docker-export
make kind-import
rm parser-gitleaks.tar.gz
make deploy
make integration-tests
```

If you are running minikube, first run `eval $(minikube -p minikube docker-env)`, then run the commands above but leave out the `docker-export` `kind-import` and `rm parser-...` commands.

2022-03-11 11:48 UTC, SebieF commented on scanners/gitleaks/Makefile
Works fine! :)  (only minor thing: the file is called `parser-gitleaks.tar`)

2022-03-11 11:48 UTC, SebieF approved these changes

2022-03-16 14:29 UTC, rseedorff approved these changes

2022-03-16 16:31 UTC, merged